### ISSUE TITLE
Change Geth settings help text

### ISSUE THREAD

**Issue by ramvi** [SilentCicero/meteor-dapp-cosmo#10]
The "Geth settings" says `--loglevel=5`. This throws an error. The setting has been changed to `--verbosity=5`

**Comment by redi-epsteinj** [comment]
A couple other comments regarding the geth command in your readme.

`unlock=primary` fails. Must be either, for example:

```
--unlock 3a842848574875b7a40da7296c36d49ed18b4c
--unlock 0                                          
```

I'd also recommend adding `--minerthreads "1"` to prevent crushing your computer, and `console`, so the user can do stuff while things run.

A non-geth suggestion: Please add a first step to the installation instructions: Install MeteorJS. I'm not a JS developer and did not understand that Meteor is a pre-requisite for Cosmo, and was convinced that the step to execute `meteor` in the `meteor-dapp-cosmo/app` directory was just an error on your part.

**Comment by ramvi** [comment]
I'm not sure if this was ever fixed or not, but it's 8 years ago, so…
